#!/usr/bin/env python3
"""Security debugger for Python and JSON files."""

import argparse
import ast
import json
import os
import re
import sys
from pathlib import Path

# ----------------------------------------------------------------------
# Patterns & checks
# ----------------------------------------------------------------------

PY_DEBUG_PATTERNS = [
    (r'\bbreakpoint\(\)', '`breakpoint()` call (PEP 553)'),
    (r'\bpdb\.set_trace\(\)', '`pdb.set_trace()`'),
    (r'\bipdb\.set_trace\(\)', '`ipdb.set_trace()`'),
    (r'\bwdb\.set_trace\(\)', '`wdb.set_trace()`'),
    (r'\brpdb\.set_trace\(\)', '`rpdb.set_trace()`'),
    (r'\bdebugpy\.breakpoint\(\)', '`debugpy.breakpoint()`'),
]

PY_SECURITY_PATTERNS = [
    (r'\beval\s*\(', '`eval()` – arbitrary code execution risk'),
    (r'\bexec\s*\(', '`exec()` – arbitrary code execution risk'),
    (r'\bcompile\s*\(', '`compile()` with user input can be dangerous'),
    (r'\bsubprocess\.(call|run|Popen)\s*\(.*shell\s*=\s*True',
     '`subprocess` with `shell=True` – command injection risk'),
    (r'\bos\.system\s*\(', '`os.system()` – command injection risk'),
    (r'\bos\.popen\s*\(', '`os.popen()` – command injection risk'),
    (r'\bpickle\.(loads|load)\s*\(', '`pickle` deserialization – unsafe'),
    (r'\byaml\.load\s*\(', '`yaml.load()` (unsafe, use `safe_load`)'),
    (r'\brequest\.get\b.*verify\s*=\s*False',
     'SSL verification disabled in requests'),
    (r'\bassert\s', '`assert` statement (may be removed with -O flag)'),
]

# Hardcoded secrets heuristics
SECRET_PATTERNS = [
    r'(password|passwd|pwd|secret|token|api_key|auth|credential)\s*[:=]\s*[\'"]\S+[\'"]'
]

# JSON checks: scan for sensitive key patterns
JSON_SENSITIVE_KEYS = [
    'password', 'passwd', 'secret', 'token', 'api_key', 'api_secret',
    'private_key', 'credential', 'auth_token'
]


# ----------------------------------------------------------------------
def scan_python_file(filepath: str) -> list[str]:
    """Return a list of findings for a single Python file."""
    findings = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception:
        return findings

    rel = os.path.relpath(filepath)

    # Debug patterns
    for pattern, desc in PY_DEBUG_PATTERNS:
        for match in re.finditer(pattern, content, re.IGNORECASE):
            lineno = content[:match.start()].count('\n') + 1
            findings.append(
                f"**DEBUG** `{match.group()}` in `{rel}:{lineno}` – {desc}"
            )

    # Security patterns
    for pattern, desc in PY_SECURITY_PATTERNS:
        for match in re.finditer(pattern, content, re.IGNORECASE):
            lineno = content[:match.start()].count('\n') + 1
            findings.append(
                f"**SECURITY** `{match.group().strip()}` in `{rel}:{lineno}` – {desc}"
            )

    # Hardcoded secrets
    for pattern in SECRET_PATTERNS:
        for match in re.finditer(pattern, content, re.IGNORECASE):
            lineno = content[:match.start()].count('\n') + 1
            findings.append(
                f"**SECRET** possible hardcoded secret in `{rel}:{lineno}`"
            )

    return findings


def scan_json_file(filepath: str) -> list[str]:
    """Return a list of findings for a JSON file."""
    findings = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception:
        return findings

    rel = os.path.relpath(filepath)

    def _walk(obj, path=""):
        if isinstance(obj, dict):
            for k, v in obj.items():
                current_path = f"{path}.{k}" if path else k
                if k.lower() in JSON_SENSITIVE_KEYS:
                    findings.append(
                        f"**SENSITIVE KEY** `{current_path}` in `{rel}`"
                    )
                _walk(v, current_path)
        elif isinstance(obj, list):
            for i, v in enumerate(obj):
                _walk(v, f"{path}[{i}]")

    _walk(data)
    return findings


def generate_md_report(findings: dict[str, list[str]]) -> str:
    """Create a Markdown report from the findings dictionary."""
    total = sum(len(v) for v in findings.values())
    if total == 0:
        return "✅ No security or debug issues found."

    lines = ["# 🔒 Security Debugger Report", ""]
    lines.append(f"**Total findings:** {total}")
    lines.append("")

    for file, items in findings.items():
        if not items:
            continue
        lines.append(f"## 📄 {file}")
        for item in items:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("---")
    lines.append("*Report generated by the Security Debugger GitHub Action.*")
    return "\n".join(lines)


# ----------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', default='.', help='Root directory to scan')
    parser.add_argument('--output', default='report.md', help='Output Markdown file')
    args = parser.parse_args()

    root = Path(args.root).resolve()
    all_findings: dict[str, list[str]] = {}

    # Collect all Python and JSON files
    py_files = list(root.rglob('*.py'))
    json_files = list(root.rglob('*.json'))

    for fp in py_files:
        findings = scan_python_file(str(fp))
        if findings:
            all_findings[str(fp.relative_to(root))] = findings

    for fp in json_files:
        findings = scan_json_file(str(fp))
        if findings:
            all_findings[str(fp.relative_to(root))] = findings

    # Generate report
    md = generate_md_report(all_findings)
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(md)

    # Set output for GitHub Actions
    issues_found = "true" if all_findings else "false"
    if 'GITHUB_OUTPUT' in os.environ:
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f"issues_found={issues_found}\n")
    print(f"issues_found={issues_found}")

    if all_findings:
        print(f"::warning::{len(all_findings)} files with findings")
        sys.exit(0)   # don't fail the job, we want the PR to be created
    else:
        print("No issues found.")

if __name__ == '__main__':
    main()